name: modflow6-examples

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.10
  - boltons
  - appdirs
  - cffconvert
  - codespell
  - filelock
  - flaky
  - fprettify
  - fortran-language-server
  - geopandas 
  - gitpython
  - Jinja2>=3.1.5,<4
  - jupytext
  - matplotlib<=3.9.4
  - meson=1.7.1
  - ninja
  - numpy
  - pip
  - pip:
      - git+https://github.com/modflowpy/flopy.git
      - git+https://github.com/modflowpy/pymake.git
      - git+https://github.com/Deltares/xmipy.git
      - git+https://github.com/MODFLOW-ORG/modflowapi.git
      - git+https://github.com/MODFLOW-ORG/modflow-devtools.git
      # docs dependencies
      - sphinx_markdown_tables
      - nbsphinx_link
      - rtds_action
      - nbconvert==7.16.3
      - nbsphinx
      - ipython
      - ipykernel
      - sphinx-rtd-theme
      - pygments>=2.4.1
      - myst-parser
  - pooch
  - pyshp
  - pytest!=8.1.0
  - pytest-benchmark
  - pytest-dotenv
  - pytest-order
  - pytest-xdist
  - python
  - pyvista
  - rasterio
  - rasterstats
  - ruff
  - scipy
  - shapely
  - syrupy
  - tomli>=2.2.1,<3
  - tomli-w>=1.2.0,<2