line-length = 88
target-version = "py39"

[lint]
select = [
    "D409", # pydocstyle - section-underline-matches-section-length
    "E",    # pycodestyle error
    "F",    # Pyflakes
    "I001", # isort - unsorted-imports
]
ignore = [
    "E501", # line too long TODO FIXME
    "E722", # do not use bare `except`
    "E741", # ambiguous variable name
    "F841", # local variable assigned but never used
]
