name: rtd

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    paths-ignore:
      - 'README.md'
      - 'DEVELOPER.md'
  pull_request:
    branches: 
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'DEVELOPER.md'
  workflow_dispatch:
jobs:
  build:
    name: Build artifacts for RTD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout MODFLOW6 examples
        uses: actions/checkout@v4
        with:
          path: modflow6-examples

      - name: Checkout MODFLOW 6
        uses: actions/checkout@v4
        with:
          repository: MODFLOW-USGS/modflow6
          path: modflow6

      - name: Show repo information
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.repository }}
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ${{ github.sha }}

      - name: Install LaTeX and extra fonts
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra texlive-science fonts-liberation
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
          sudo rm -rf ~/.cache/matplotlib

      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-linux-amd64.tar.gz
          sudo tar xvzf pandoc-2.11.2-linux-amd64.tar.gz --strip-components=1 -C /usr/local
          pandoc --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@v2

      - name: Install Python packages
        working-directory: modflow6-examples/etc
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.pip.txt
          pip install -r requirements.usgs.txt
          python -m ipykernel install --name python_kernel --user

      - name: Update FloPy classes
        run: python -m flopy.mf6.utils.generate_classes --ref develop --no-backup

      - name: Install MODFLOW executables
        uses: modflowpy/install-modflow-action@v1

      - name: Build MODFLOW 6
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir
          cp bin/* ~/.local/bin/modflow/
      
      - name: Run notebooks, make plots
        working-directory: modflow6-examples/autotest
        run: pytest -v -n=auto --durations=0 test_notebooks.py --plot

      - name: Run postprocessing
        working-directory: modflow6-examples/scripts
        run: python process-scripts.py

      - name: Create Markdown tables
        working-directory: modflow6-examples/etc
        run: python ci_create_examples_rst.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rtd-files-for-${{ github.sha }}
          path: |
            modflow6-examples/.doc/introduction.md
            modflow6-examples/.doc/examples.rst
            modflow6-examples/.doc/_examples
            modflow6-examples/.doc/_images
            modflow6-examples/.doc/_notebooks

  trigger:
    name: Trigger RTD build
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'MODFLOW-USGS' &&
      (
        github.ref_name == 'master' ||
        github.ref_name == 'develop'
      ) && (
        github.event_name == 'push' ||
        github.event_name == 'workflow_dispatch'
      )
    steps:
      - name: Checkout MODFLOW6 examples repo
        uses: actions/checkout@v4

      - name: Trigger RTD build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
