name: rtd

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rtd_build:
    name: rtd-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      script-directory: scripts
      etc-directory: etc
    defaults:
      run:
        shell: bash -l {0}

    if: github.repository_owner == 'MODFLOW-USGS'
    steps:
      - name: Checkout MODFLOW6 examples repo
        uses: actions/checkout@v2.3.4

      - name: Output repo information
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.repository }}
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ${{ github.sha }}

      - name: Setup symbolic link to gfortran
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Install TeX Live and additional TrueType fonts
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra texlive-science fonts-liberation

      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-linux-amd64.tar.gz
          sudo tar xvzf pandoc-2.11.2-linux-amd64.tar.gz --strip-components=1 -C /usr/local
          pandoc --version

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: mf6ex
          environment-file: etc/dependencies.yml

      - name: Add packages to mf6ex environment using pip
        run: |
          pip install -r requirements.usgs.txt
        working-directory: ${{env.etc-directory}}

      - name: Run get_exes script
        run: |
          python ci_get_exes.py
        working-directory: ${{env.etc-directory}}

      - name: Run scripts to build model files
        run: |
          python ci_build_files.py
        working-directory: ${{env.etc-directory}}

      - name: Run processing script
        run: |
          python process-scripts.py
        working-directory: ${{env.script-directory}}

      - name: Run notebooks with jupytext for ReadtheDocs
        run: |
          python ci_run_notebooks.py
        working-directory: ${{env.etc-directory}}

      - name: Create package tables and examples.rst for ReadtheDocs
        run: |
          python ci_create_examples_rst.py
        working-directory: ${{env.etc-directory}}

      - name: List example rst files for ReadtheDocs
        run: |
          ls -l .doc/_examples/

      - name: List example image files for ReadtheDocs
        run: |
          ls -l .doc/_images/

      - name: List example notebook files for ReadtheDocs
        run: |
          ls -l .doc/_notebooks/

      - name: Upload completed jupyter notebooks as an artifact for ReadtheDocs
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: rtd-files-for-${{ github.sha }}
          path: |
            .doc/introduction.md
            .doc/examples.rst
            .doc/_examples
            .doc/_images
            .doc/_notebooks

  # trigger rtd if "rtd_build" job was successful
  rtd_trigger:
    name: rtd-trigger
    needs: rtd_build
    runs-on: ubuntu-latest

    if: github.repository_owner == 'MODFLOW-USGS' && github.event_name == 'push'
    steps:
      - name: Checkout MODFLOW6 examples repo
        uses: actions/checkout@v2.3.4

      - name: Trigger RTDs build on push to repo branches
        uses: dfm/rtds-action@v1.0.2
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
