name: CI

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: current-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      script-directory: scripts
      etc-directory: etc
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MODFLOW6 examples repo
        uses: actions/checkout@v2.3.4

      - name: Output repo information
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.repository }}
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ${{ github.sha }}

      - name: Setup symbolic link to gfortran
        run: |
          sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
          sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
          sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

      - name: Install TeX Live and additional TrueType fonts
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra texlive-science fonts-liberation

      - name: Setup Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Print python version
        run: |
          python --version

      - name: Install Python 3.8 packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.pip.txt
          pip install -r requirements.usgs.txt
        working-directory: ${{env.etc-directory}}

      - name: Run get_exes script
        run: |
          python ci_get_exes.py
        working-directory: ${{env.etc-directory}}

      - name: List executables
        run: |
          ls -l ./bin/

      - name: Run scripts without model runs and zip input files
        run: |
          python ci_build_files.py --zip
        working-directory: ${{env.etc-directory}}

      - name: Run scripts plus processing script
        run: |
          nosetests -v --with-id --with-timer ex-*
          python process-scripts.py
        working-directory: ${{env.script-directory}}

      - name: Build mf6examples LaTeX document
        shell: python
        run: |
          import sys
          import subprocess

          ws = "./doc/"
          bibnam = "mf6examples"
          texnam = bibnam + ".tex"
          args = (
                  ("pdflatex", texnam),
                  ("bibtex", bibnam),
                  ("pdflatex", texnam),
                  ("pdflatex", texnam),
                 )
          for arg in args:
              print("running command...'{}'".format(" ".join(arg)))
              with subprocess.Popen(arg,
                                    stdout=subprocess.PIPE,
                                    stderr=subprocess.STDOUT,
                                    cwd=ws) as process:
                  stdout, stderr = process.communicate(timeout=60)
                  if stdout:
                      stdout = stdout.decode()
                      print(stdout)
                  if stderr:
                      print("\n\nError condition occurred:\n")
                      stderr = stderr.decode()
                      print(stderr)

      - name: Rename and move the LaTeX document
        run: |
          ls -l ./doc/
          mv ./doc/mf6examples.pdf mf6examples.pdf
          ls -l ./

      - name: Upload build artifacts for current release
        if:
          github.repository_owner == 'MODFLOW-USGS' && github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: current
          path: |
            ./mf6examples.pdf
            ./modflow6-examples.zip


  # make the release if the "build" job was successful
  release:
    name: Make the release
    needs: build
    runs-on: ubuntu-latest

    if: github.repository_owner == 'MODFLOW-USGS' && github.event_name == 'push'
    steps:
      - name: Checkout MODFLOW6 examples repo
        uses: actions/checkout@v2

      - name: Get Current Time
        uses: 1466587594/get-current-time@v2.0.0
        id: current-time
        with:
          format: MM/DD/YYYY HH:mm

      - name: Set current time as environmental variable
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: |
          echo "F_TIME=${{ steps.current-time.outputs.formattedTime }}" >> $GITHUB_ENV
          echo "TIME=${{ steps.current-time.outputs.time }}" >> $GITHUB_ENV
          echo $TIME
          echo $F_TIME
          echo "MODFLOW 6 examples: built at ${F_TIME}"

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: current
          path: ./current/

      - name: List files in the artifact directory
        run: |
          pwd
          ls -l ./current/

      - name: create bodyFile
        run: |
          echo "MODFLOW 6 examples: built "${F_TIME} > bodyFile
          cat bodyFile
          ls -l .

      - name: Delete the latest release
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update the current release
        uses: ncipollo/release-action@v1
        with:
          tag: current
          name: current build
          bodyFile: ./bodyFile
          allowUpdates: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MODFLOW 6 examples to the current GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./current/*
          tag: current
          overwrite: true
          file_glob: true

      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: current
